import { Type } from '../bean/Type'

export const TYPE_DATA: Type[] = [
  new Type(
    '水产',
    'Aquatic Food',
    $r('app.media.startIcon'),
    ['咖喱炒蟹', '小龙虾', '微波葱姜黑鳕鱼']
  ),
  new Type(
    '早餐',
    'Breakfast',
    $r('app.media.startIcon'),
    []
  ),
  new Type(
    '佐料',
    'Condiment',
    $r('app.media.startIcon'),
    []
  ),
  new Type(
    '甜品',
    'Dessert',
    $r('app.media.startIcon'),
    []
  ),
  new Type(
    '饮品',
    'Drink',
    $r('app.media.startIcon'),
    []
  ),
  new Type(
    '烹饪',
    'Cooking',
    $r('app.media.startIcon'),
    []
  ),
  new Type(
    '荤菜',
    'Meat',
    $r('app.media.startIcon'),
    []
  ),
  new Type(
    '速食',
    'Fast Food',
    $r('app.media.startIcon'),
    []
  ),
  new Type(
    '汤',
    'Soup',
    $r('app.media.startIcon'),
    []
  ),
  new Type(
    '主食',
    'Staple',
    $r('app.media.startIcon'),
    []
  ),
  new Type(
    '素菜',
    'Vegetable',
    $r('app.media.startIcon'),
    []
  ),
]